# GitHub Sponsors funding configuration

# GitHub username for sponsoring
# github: [vibheksoni]

# Buy me a coffee
custom: ["https://buymeacoffee.com/vibheksoni"]

# Cryptocurrency donations
# Bitcoin: 3QaS5hq2416Gd3386M6c9g5Dgc5RgvP3o2
# Litecoin: MM35KN1wUXREpwjj2RsmiKHM1ZWKDmeqDz
# Solana: 3LkBXDKLZXAgCRzAApa6dQG3ba7zRkUK82Bvmd9JWMdi