name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
assignees: ["vibheksoni"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details about what you'd like to see added.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered?
      placeholder: I also considered...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for adoption
    validations:
      required: true

  - type: checkboxes
    id: area
    attributes:
      label: Feature Area
      description: Which area does this feature relate to?
      options:
        - label: Authentication
        - label: Portfolio Management
        - label: Trading Operations
        - label: Market Data
        - label: WebSocket Streaming
        - label: Documentation
        - label: Examples
        - label: Performance
        - label: Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the feature request