name: Question
description: Ask a question about using axiomtrade-rs
title: "[Question]: "
labels: ["question"]
assignees: ["vibheksoni"]

body:
  - type: markdown
    attributes:
      value: |
        Have a question about using axiomtrade-rs? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What area is your question about?
      options:
        - Getting Started
        - Authentication & OTP
        - Portfolio Management
        - Trading Operations
        - WebSocket Streaming
        - Error Handling
        - Performance
        - Examples
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context that might help us answer your question
      placeholder: I'm trying to... and I've already tried...

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: If relevant, please share the code you're working with
      render: rust