[book]
title = "axiomtrade-rs Documentation"
description = "Complete guide to using the axiomtrade-rs Solana trading SDK"
authors = ["Vibhek Soni"]
language = "en"
multilingual = false
src = "src"

[rust]
edition = "2024"

[build]
build-dir = "book"
create-missing = true

[preprocessor.links]

[output.html]
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/vibheksoni/axiomtrade-rs"
edit-url-template = "https://github.com/vibheksoni/axiomtrade-rs/edit/master/docs/{path}"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = false
runnable = true